### ISSUE TITLE
[BUG]: `BEST` option `effect_magnitude` raises

### ISSUE THREAD

**Issue by AlexRodis** [AlexRodis/bayesian-models#68]
Attempting to call `BEST` with the `effect_magnitude=True` option raises `KeyError: 'Effect_Size(setosa, versicolor)'`. MRE:
```
from sklearn.datasets import load_iris
from bayesian_models.models import BEST
import pandas as pd

X, y = load_iris(return_X_y=True, as_frame=True)
names=load_iris().target_names
y=y.replace({i:names[i] for i in range(len(names))})
 df = pd.concat([X,y], axis=1)
 BEST.std_upper = 1e3
BEST.std_lower = 1e-3
obj = BEST()(df, "target")
obj = BEST(std_difference=True, effect_magnitude=True)(df, "target")
# Raises:
# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/bayesian_models/bayeisan_models_release/tenv/lib/python3.10/site-packages/bayesian_models/models.py", line 1034, in __call__
    builder()
#  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/bayesian_models/bayeisan_models_release/tenv/lib/python3.10/site-packages/bayesian_models/core.py", line 884, in __call__
#    return self.builder()
#  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/bayesian_models/bayeisan_models_release/tenv/lib/python3.10/site-packages/bayesian_models/core.py", line 837, in __call__
    self.build()
#  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/bayesian_models/bayeisan_models_release/tenv/lib/python3.10/site-packages/bayesian_models/core.py", line 795, in build
#    self.core_model()
#  File "/media/alexander-fyrogenis/Elements/Διδακτορικό/bayesian_models/bayeisan_models_release/tenv/lib/python3.10/site-packages/bayesian_models/core.py", line 667, in __call__
#    self.variables[v_name_magnitude].append(
KeyError: 'Effect_Size(setosa, versicolor)'

```

**Comment by AlexRodis** [comment]
closed by PR #72
